export enum EventKind {
  SESSION_START = 'SESSION_START',
  SESSION_END = 'SESSION_END',
  USER_INPUT = 'USER_INPUT',
  ASSISTANT_TEXT_START = 'ASSISTANT_TEXT_START',
  ASSISTANT_TEXT_DELTA = 'ASSISTANT_TEXT_DELTA',
  ASSISTANT_TEXT_END = 'ASSISTANT_TEXT_END',
  TOOL_CALL_START = 'TOOL_CALL_START',
  TOOL_CALL_OUTPUT_DELTA = 'TOOL_CALL_OUTPUT_DELTA',
  TOOL_CALL_END = 'TOOL_CALL_END',
  STEERING_INJECTED = 'STEERING_INJECTED',
  TURN_LIMIT = 'TURN_LIMIT',
  LOOP_DETECTION = 'LOOP_DETECTION',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
}

export interface SessionEvent {
  kind: EventKind
  timestamp: Date
  session_id: string
  data: Record<string, unknown>
}
